// Generated by https://quicktype.io
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:poynt_hackathon/feature/Products/data/models/product_model.dart';
part 'product_api_reponse.freezed.dart';
part 'product_api_reponse.g.dart';

@freezed
class ProductApiResponse with _$ProductApiResponse {
  const factory ProductApiResponse({
    required List<PYProductModel> data,
  }) = _ProductApiResponse;

  factory ProductApiResponse.fromJson(Map<String, dynamic> json) => _$ProductApiResponseFromJson(json);
}
